# Generated by Django 5.1.3 on 2024-11-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='something@gmail.com', max_length=254, unique=True),
        ),
    ]
